NAME = Einsteinium_Preferences
TYPE = APP
APP_MIME_SIG = application/x-vnd.Einsteinium_Preferences
SRCS = ../Common/methods.cpp \
		../Daemon/AppRelaunchSettings.cpp \
		../Daemon/EDSettingsFile.cpp \
		AppRefFilter.cpp \
		BitmapListItem.cpp \
		LauncherAboutView.cpp \
		EngineMaintenanceView.cpp \
		EngineStatusView.cpp \
		DaemonRelaunchView.cpp \
		DaemonStatusView.cpp \
		SystemStatusBox.cpp \
		prefsWindow.cpp \
		prefs_app.cpp \
		main.cpp
LIBS = be localestub tracker $(STDCPPLIBS) xml2
OPTIMIZE = FULL
RDEFS = einsteinium_prefs.rdef

#	Specify additional paths to directories following the standard libXXX.so
#	or libXXX.a naming scheme. You can specify full paths or paths relative
#	to the Makefile. The paths included are not parsed recursively, so
#	include all of the paths where libraries must be found. Directories where
#	source files were specified are	automatically included.
LIBPATHS =

#	Additional paths to look for system headers. These use the form
#	"#include <header>". Directories that contain the files in SRCS are
#	NOT auto-included here.
SYSTEM_INCLUDE_PATHS = /boot/system/develop/headers/libxml2

#	Additional paths paths to look for local headers. These use the form
#	#include "header". Directories that contain the files in SRCS are
#	automatically included.
LOCAL_INCLUDE_PATHS = ../Common ../Engine ../Launcher

# 	Specify the codes for languages you are going to support in this
# 	application. The default "en" one must be provided too. "make catkeys"
# 	will recreate only the "locales/en.catkeys" file. Use it as a template
# 	for creating catkeys for other languages. All localization files must be
# 	placed in the "locales" subdirectory.
LOCALES = de en

#	Specify all the preprocessor symbols to be defined. The symbols will not
#	have their values set automatically; you must supply the value (if any) to
#	use. For example, setting DEFINES to "DEBUG=1" will cause the compiler
#	option "-DDEBUG=1" to be used. Setting DEFINES to "DEBUG" would pass
#	"-DDEBUG" on the compiler's command line.
DEFINES =

#	Specify the warning level. Either NONE (suppress all warnings),
#	ALL (enable all warnings), or leave blank (enable default warnings).
WARNINGS =

#	With image symbols, stack crawls in the debugger are meaningful.
#	If set to "TRUE", symbols will be created.
SYMBOLS :=

#	Includes debug information, which allows the binary to be debugged easily.
#	If set to "TRUE", debug info will be created.
DEBUGGER :=

#	Specify any additional compiler flags to be used.
COMPILER_FLAGS =

#	Specify any additional linker flags to be used.
LINKER_FLAGS =

#	Specify the version of this binary. Example:
#		-app 3 4 0 d 0 -short 340 -long "340 "`echo -n -e '\302\251'`"1999 GNU GPL"
#	This may also be specified in a resource.
APP_VERSION :=

#       Specify if you want the object files to be somewhere besides the default location.
OBJ_DIR := _Pobjects

#       Specify a non default placement for the target
TARGET_DIR := .

## Include the Makefile-Engine
DEVEL_DIRECTORY := \
	$(shell findpaths -r "makefile_engine" B_FIND_PATH_DEVELOP_DIRECTORY)
include $(DEVEL_DIRECTORY)/etc/makefile-engine
